
var response = [{
  "host":"127.0.0.1",
  "stats":{
    "name":"MacBook-Pro.local",
    "timestamp":1442559482116,
    "total":100,
    "use":(Math.random()*100).toFixed(),
    "license":[{
      "name":"BIOLUMINATE_MAIN",
      "total":10,
      "use":(Math.random()*10).toFixed()
    },{
      "name":"BIOLUMINATE_PROTEIN_DOCKING",
      "total":10,
      "use":(Math.random()*10).toFixed()
    },{
      "name":"BIOLUMINATE_SHARED",
      "total":10,
      "use":(Math.random()*10).toFixed()
    },{
      "name":"CANVAS_ELEMENTS",
      "total":100,
      "use":(Math.random()*10).toFixed()
    },{
      "name":"CANVAS_MAIN",
      "total":50,
      "use":(Math.random()*50).toFixed()
    },{
      "name":"CANVAS_SHARED",
      "total":1000,
      "use":(Math.random()*1000).toFixed()
    },{
      "name":"KNIME_MAIN",
      "total":50,
      "use":(Math.random()*50).toFixed()
    },{
      "name":"MAESTRO_MAIN",
      "total":1000,
      "use":(Math.random()*1000).toFixed()
    },{
      "name":"MMLIBS",
      "total":1000,
      "use":0
    },{
      "name":"MMOD_CONFGEN",
      "total":104,
      "use":0
    },{
      "name":"MMOD_MBAE",
      "total":20,
      "use":0
    },{
      "name":"SUITE_05MAR2015",
      "total":40,
      "use":8
    },{
      "name":"ADME_P450",
      "total":40,
      "use":0
    },{
      "name":"CANVAS_FULL",
      "total":40,
      "use":0
    },{
      "name":"COMBIGLIDE_CORE_HOPPING",
      "total":40,
      "use":0
    },{
      "name":"COMBIGLIDE_MAIN",
      "total":40,
      "use":0
    },{
      "name":"DESMOND_MAIN",
      "total":40,
      "use":0
    },{
      "name":"EPIK_MAIN",
      "total":40,
      "use":0
    },{
      "name":"GLIDE_COMBIGLIDE",
      "total":40,
      "use":0
    },{
      "name":"GLIDE_CORE_HOPPING",
      "total":40,
      "use":0
    },{
      "name":"GLIDE_MAIN",
      "total":40,
      "use":0
    },{
      "name":"GLIDE_PRIMEX_LIGFIT",
      "total":40,
      "use":0
    },{
      "name":"GLIDE_SP_DOCKING",
      "total":40,
      "use":0
    },{
      "name":"GLIDE_XP_DESC",
      "total":40,
      "use":0
    },{
      "name":"GLIDE_XP_DOCKING",
      "total":40,
      "use":0
    },{
      "name":"IMPACT_MAIN",
      "total":40,
      "use":0
    },{
      "name":"JAGUAR_MAIN",
      "total":40,
      "use":0
    },{
      "name":"JAGUAR_PKA",
      "total":40,
      "use":0
    },{
      "name":"JAGUAR_QSITE",
      "total":40,
      "use":0
    },{
      "name":"LIAISON_MAIN",
      "total":40,
      "use":0
    },{
      "name":"LIGPREP_MAIN",
      "total":40,
      "use":0
    },{
      "name":"MMOD_MACROMODEL",
      "total":40,
      "use":0
    },{
      "name":"PHASE_CORE_HOPPING",
      "total":40,
      "use":0
    },{
      "name":"PHASE_DBCREATE",
      "total":40,
      "use":0
    },{
      "name":"PHASE_DBSEARCH",
      "total":40,
      "use":0
    },{
      "name":"PHASE_FEATURE",
      "total":40,
      "use":0
    },{
      "name":"PHASE_FQSAR",
      "total":40,
      "use":0
    },{
      "name":"PHASE_PARTITION",
      "total":40,
      "use":0
    },{
      "name":"PHASE_QSAR",
      "total":40,
      "use":0
    },{
      "name":"PHASE_SCORING",
      "total":40,
      "use":0
    },{
      "name":"PHASE_SELECTIVITY",
      "total":40,
      "use":0
    },{
      "name":"PRIMEX_LIGPREP_EPIK",
      "total":40,
      "use":0
    },{
      "name":"PRIMEX_MAIN",
      "total":40,
      "use":0
    },{
      "name":"PSP_BB",
      "total":40,
      "use":0
    },{
      "name":"PSP_FR",
      "total":40,
      "use":0
    },{
      "name":"PSP_PLOP",
      "total":40,
      "use":8
    },{
      "name":"PSP_PLOP_MEMBRANE",
      "total":40,
      "use":0
    },{
      "name":"PSP_RB",
      "total":40,
      "use":0
    },{
      "name":"PSP_SKA",
      "total":40,
      "use":0
    },{
      "name":"PSP_SSP",
      "total":40,
      "use":0
    },{
      "name":"PSP_STA",
      "total":40,
      "use":0
    },{
      "name":"PSP_STA_GPCR",
      "total":40,
      "use":0
    },{
      "name":"QIKPROP_MAIN",
      "total":40,
      "use":0
    },{
      "name":"SITEMAP_MAIN",
      "total":40,
      "use":0
    },{
      "name":"STRIKE_MAIN",
      "total":40,
      "use":0
    }]
  }
},
    {
        "host":"http://192.168.30.228/",
        "stats":{
            "name":"Another 1",
            "timestamp":1442559482116,
            "total":100,
            "use":(Math.random()*100).toFixed(),
            "license":[{
                "name":"BIOLUMINATE_MAIN",
                "total":10,
                "use":0
            },{
                "name":"BIOLUMINATE_PROTEIN_DOCKING",
                "total":10,
                "use":0
            },{
                "name":"BIOLUMINATE_SHARED",
                "total":10,
                "use":0
            },{
                "name":"CANVAS_ELEMENTS",
                "total":100,
                "use":0
            },{
                "name":"CANVAS_MAIN",
                "total":50,
                "use":0
            },{
                "name":"CANVAS_SHARED",
                "total":1000,
                "use":0
            },{
                "name":"KNIME_MAIN",
                "total":50,
                "use":0
            },{
                "name":"MAESTRO_MAIN",
                "total":1000,
                "use":2
            },{
                "name":"MMLIBS",
                "total":1000,
                "use":0
            },{
                "name":"MMOD_CONFGEN",
                "total":104,
                "use":0
            },{
                "name":"MMOD_MBAE",
                "total":20,
                "use":0
            },{
                "name":"SUITE_05MAR2015",
                "total":40,
                "use":8
            },{
                "name":"ADME_P450",
                "total":40,
                "use":0
            },{
                "name":"CANVAS_FULL",
                "total":40,
                "use":0
            },{
                "name":"COMBIGLIDE_CORE_HOPPING",
                "total":40,
                "use":0
            },{
                "name":"COMBIGLIDE_MAIN",
                "total":40,
                "use":0
            },{
                "name":"DESMOND_MAIN",
                "total":40,
                "use":0
            },{
                "name":"EPIK_MAIN",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_COMBIGLIDE",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_CORE_HOPPING",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_MAIN",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_PRIMEX_LIGFIT",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_SP_DOCKING",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_XP_DESC",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_XP_DOCKING",
                "total":40,
                "use":0
            },{
                "name":"IMPACT_MAIN",
                "total":40,
                "use":0
            },{
                "name":"JAGUAR_MAIN",
                "total":40,
                "use":0
            },{
                "name":"JAGUAR_PKA",
                "total":40,
                "use":0
            },{
                "name":"JAGUAR_QSITE",
                "total":40,
                "use":0
            },{
                "name":"LIAISON_MAIN",
                "total":40,
                "use":0
            },{
                "name":"LIGPREP_MAIN",
                "total":40,
                "use":0
            },{
                "name":"MMOD_MACROMODEL",
                "total":40,
                "use":0
            },{
                "name":"PHASE_CORE_HOPPING",
                "total":40,
                "use":0
            },{
                "name":"PHASE_DBCREATE",
                "total":40,
                "use":0
            },{
                "name":"PHASE_DBSEARCH",
                "total":40,
                "use":0
            },{
                "name":"PHASE_FEATURE",
                "total":40,
                "use":0
            },{
                "name":"PHASE_FQSAR",
                "total":40,
                "use":0
            },{
                "name":"PHASE_PARTITION",
                "total":40,
                "use":0
            },{
                "name":"PHASE_QSAR",
                "total":40,
                "use":0
            },{
                "name":"PHASE_SCORING",
                "total":40,
                "use":0
            },{
                "name":"PHASE_SELECTIVITY",
                "total":40,
                "use":0
            },{
                "name":"PRIMEX_LIGPREP_EPIK",
                "total":40,
                "use":0
            },{
                "name":"PRIMEX_MAIN",
                "total":40,
                "use":0
            },{
                "name":"PSP_BB",
                "total":40,
                "use":0
            },{
                "name":"PSP_FR",
                "total":40,
                "use":0
            },{
                "name":"PSP_PLOP",
                "total":40,
                "use":8
            },{
                "name":"PSP_PLOP_MEMBRANE",
                "total":40,
                "use":0
            },{
                "name":"PSP_RB",
                "total":40,
                "use":0
            },{
                "name":"PSP_SKA",
                "total":40,
                "use":0
            },{
                "name":"PSP_SSP",
                "total":40,
                "use":0
            },{
                "name":"PSP_STA",
                "total":40,
                "use":0
            },{
                "name":"PSP_STA_GPCR",
                "total":40,
                "use":0
            },{
                "name":"QIKPROP_MAIN",
                "total":40,
                "use":0
            },{
                "name":"SITEMAP_MAIN",
                "total":40,
                "use":0
            },{
                "name":"STRIKE_MAIN",
                "total":40,
                "use":0
            }]
        }
    }
];



var response2 = [{
    "host":"127.0.0.1",
    "stats":{
        "name":"MacBook-Pro.local",
        "timestamp":1442559482116,
        "license":[{
            "name":"BIOLUMINATE_MAIN",
            "total":10,
            "use":1
        },{
            "name":"BIOLUMINATE_PROTEIN_DOCKING",
            "total":10,
            "use":5
        },{
            "name":"BIOLUMINATE_SHARED",
            "total":10,
            "use":3
        },{
            "name":"CANVAS_ELEMENTS",
            "total":100,
            "use":99.5
        },{
            "name":"CANVAS_MAIN",
            "total":50,
            "use":10
        },{
            "name":"CANVAS_SHARED",
            "total":1000,
            "use":0
        },{
            "name":"KNIME_MAIN",
            "total":50,
            "use":0
        },{
            "name":"MAESTRO_MAIN",
            "total":1000,
            "use":2
        },{
            "name":"MMLIBS",
            "total":1000,
            "use":0
        },{
            "name":"MMOD_CONFGEN",
            "total":104,
            "use":0
        },{
            "name":"MMOD_MBAE",
            "total":20,
            "use":0
        },{
            "name":"SUITE_05MAR2015",
            "total":40,
            "use":8
        },{
            "name":"ADME_P450",
            "total":40,
            "use":0
        },{
            "name":"CANVAS_FULL",
            "total":40,
            "use":0
        },{
            "name":"COMBIGLIDE_CORE_HOPPING",
            "total":40,
            "use":0
        },{
            "name":"COMBIGLIDE_MAIN",
            "total":40,
            "use":0
        },{
            "name":"DESMOND_MAIN",
            "total":40,
            "use":0
        },{
            "name":"EPIK_MAIN",
            "total":40,
            "use":0
        },{
            "name":"GLIDE_COMBIGLIDE",
            "total":40,
            "use":0
        },{
            "name":"GLIDE_CORE_HOPPING",
            "total":40,
            "use":0
        },{
            "name":"GLIDE_MAIN",
            "total":40,
            "use":0
        },{
            "name":"GLIDE_PRIMEX_LIGFIT",
            "total":40,
            "use":0
        },{
            "name":"GLIDE_SP_DOCKING",
            "total":40,
            "use":0
        },{
            "name":"GLIDE_XP_DESC",
            "total":40,
            "use":0
        },{
            "name":"GLIDE_XP_DOCKING",
            "total":40,
            "use":0
        },{
            "name":"IMPACT_MAIN",
            "total":40,
            "use":0
        },{
            "name":"JAGUAR_MAIN",
            "total":40,
            "use":0
        },{
            "name":"JAGUAR_PKA",
            "total":40,
            "use":0
        },{
            "name":"JAGUAR_QSITE",
            "total":40,
            "use":0
        },{
            "name":"LIAISON_MAIN",
            "total":40,
            "use":0
        },{
            "name":"LIGPREP_MAIN",
            "total":40,
            "use":0
        },{
            "name":"MMOD_MACROMODEL",
            "total":40,
            "use":0
        },{
            "name":"PHASE_CORE_HOPPING",
            "total":40,
            "use":0
        },{
            "name":"PHASE_DBCREATE",
            "total":40,
            "use":0
        },{
            "name":"PHASE_DBSEARCH",
            "total":40,
            "use":0
        },{
            "name":"PHASE_FEATURE",
            "total":40,
            "use":0
        },{
            "name":"PHASE_FQSAR",
            "total":40,
            "use":0
        },{
            "name":"PHASE_PARTITION",
            "total":40,
            "use":0
        },{
            "name":"PHASE_QSAR",
            "total":40,
            "use":0
        },{
            "name":"PHASE_SCORING",
            "total":40,
            "use":0
        },{
            "name":"PHASE_SELECTIVITY",
            "total":40,
            "use":0
        },{
            "name":"PRIMEX_LIGPREP_EPIK",
            "total":40,
            "use":0
        },{
            "name":"PRIMEX_MAIN",
            "total":40,
            "use":0
        },{
            "name":"PSP_BB",
            "total":40,
            "use":0
        },{
            "name":"PSP_FR",
            "total":40,
            "use":0
        },{
            "name":"PSP_PLOP",
            "total":40,
            "use":8
        },{
            "name":"PSP_PLOP_MEMBRANE",
            "total":40,
            "use":0
        },{
            "name":"PSP_RB",
            "total":40,
            "use":0
        },{
            "name":"PSP_SKA",
            "total":40,
            "use":0
        },{
            "name":"PSP_SSP",
            "total":40,
            "use":0
        },{
            "name":"PSP_STA",
            "total":40,
            "use":0
        },{
            "name":"PSP_STA_GPCR",
            "total":40,
            "use":0
        },{
            "name":"QIKPROP_MAIN",
            "total":40,
            "use":0
        },{
            "name":"SITEMAP_MAIN",
            "total":40,
            "use":0
        },{
            "name":"STRIKE_MAIN",
            "total":40,
            "use":0
        }]
    }
},
    {
        "host":"http://192.168.30.228/",
        "stats":{
            "name":"Another 1",
            "timestamp":1442559482116,
            "license":[{
                "name":"BIOLUMINATE_MAIN",
                "total":10,
                "use":8
            },{
                "name":"BIOLUMINATE_PROTEIN_DOCKING",
                "total":10,
                "use":5
            },{
                "name":"BIOLUMINATE_SHARED",
                "total":10,
                "use":0
            },{
                "name":"CANVAS_ELEMENTS",
                "total":100,
                "use":15
            },{
                "name":"CANVAS_MAIN",
                "total":50,
                "use":0
            },{
                "name":"CANVAS_SHARED",
                "total":1000,
                "use":0
            },{
                "name":"KNIME_MAIN",
                "total":50,
                "use":0
            },{
                "name":"MAESTRO_MAIN",
                "total":1000,
                "use":2
            },{
                "name":"MMLIBS",
                "total":1000,
                "use":0
            },{
                "name":"MMOD_CONFGEN",
                "total":104,
                "use":0
            },{
                "name":"MMOD_MBAE",
                "total":20,
                "use":0
            },{
                "name":"SUITE_05MAR2015",
                "total":40,
                "use":8
            },{
                "name":"ADME_P450",
                "total":40,
                "use":0
            },{
                "name":"CANVAS_FULL",
                "total":40,
                "use":0
            },{
                "name":"COMBIGLIDE_CORE_HOPPING",
                "total":40,
                "use":0
            },{
                "name":"COMBIGLIDE_MAIN",
                "total":40,
                "use":0
            },{
                "name":"DESMOND_MAIN",
                "total":40,
                "use":0
            },{
                "name":"EPIK_MAIN",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_COMBIGLIDE",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_CORE_HOPPING",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_MAIN",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_PRIMEX_LIGFIT",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_SP_DOCKING",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_XP_DESC",
                "total":40,
                "use":0
            },{
                "name":"GLIDE_XP_DOCKING",
                "total":40,
                "use":0
            },{
                "name":"IMPACT_MAIN",
                "total":40,
                "use":0
            },{
                "name":"JAGUAR_MAIN",
                "total":40,
                "use":0
            },{
                "name":"JAGUAR_PKA",
                "total":40,
                "use":0
            },{
                "name":"JAGUAR_QSITE",
                "total":40,
                "use":0
            },{
                "name":"LIAISON_MAIN",
                "total":40,
                "use":0
            },{
                "name":"LIGPREP_MAIN",
                "total":40,
                "use":0
            },{
                "name":"MMOD_MACROMODEL",
                "total":40,
                "use":0
            },{
                "name":"PHASE_CORE_HOPPING",
                "total":40,
                "use":0
            },{
                "name":"PHASE_DBCREATE",
                "total":40,
                "use":0
            },{
                "name":"PHASE_DBSEARCH",
                "total":40,
                "use":0
            },{
                "name":"PHASE_FEATURE",
                "total":40,
                "use":0
            },{
                "name":"PHASE_FQSAR",
                "total":40,
                "use":0
            },{
                "name":"PHASE_PARTITION",
                "total":40,
                "use":0
            },{
                "name":"PHASE_QSAR",
                "total":40,
                "use":0
            },{
                "name":"PHASE_SCORING",
                "total":40,
                "use":0
            },{
                "name":"PHASE_SELECTIVITY",
                "total":40,
                "use":0
            },{
                "name":"PRIMEX_LIGPREP_EPIK",
                "total":40,
                "use":0
            },{
                "name":"PRIMEX_MAIN",
                "total":40,
                "use":0
            },{
                "name":"PSP_BB",
                "total":40,
                "use":0
            },{
                "name":"PSP_FR",
                "total":40,
                "use":0
            },{
                "name":"PSP_PLOP",
                "total":40,
                "use":8
            },{
                "name":"PSP_PLOP_MEMBRANE",
                "total":40,
                "use":0
            },{
                "name":"PSP_RB",
                "total":40,
                "use":0
            },{
                "name":"PSP_SKA",
                "total":40,
                "use":0
            },{
                "name":"PSP_SSP",
                "total":40,
                "use":0
            },{
                "name":"PSP_STA",
                "total":40,
                "use":0
            },{
                "name":"PSP_STA_GPCR",
                "total":40,
                "use":0
            },{
                "name":"QIKPROP_MAIN",
                "total":40,
                "use":0
            },{
                "name":"SITEMAP_MAIN",
                "total":40,
                "use":0
            },{
                "name":"STRIKE_MAIN",
                "total":40,
                "use":0
            }]
        }
    }
]